In [1]:
import numpy as np

# creating a 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [2]:
# creating a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
# basic operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

print(a + b) # elementwise addition
print(a - b) # elementwise subtraction
print(a * b) # elementwise multiplication
print(a / b) # elementwise division
print(a ** b) # elementwise power
print(a % b) # elementwise modulo
print(a // b) # elementwise floor division
print(a + 3) # add 3 to each element

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[ 1 16 27 16  5]
[1 2 0 0 0]
[0 0 1 2 5]
[4 5 6 7 8]


In [9]:
# matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b)) 

[[19 22]
 [43 50]]


In [31]:
# using special functions
a = np.zeros((2, 2)) # creates a 2x2 matrix with zeros
print(a)

b = np.ones((1, 2)) # creates a 1x2 matrix with ones
print(b)

c = np.full((2, 2), 7) # creates a 2x2 matrix with all elements as 7
print(c)

d = np.eye(2) # creates a 2x2 identity matrix
print(d)

e = np.random.random((2, 2)) # creates a 2x2 matrix with random numbers
print(e)

# sum of all elements
a = np.array([[1, 2], [3, 4]])
print(np.sum(a))

# sum of each column
print(np.sum(a, axis=0))

# sum of each row
print(np.sum(a, axis=1))

# transpose
print(a.T)

# reshaping
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.reshape(3, 2))

# stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a, b))) # vertical stack
print(np.hstack((a, b))) # horizontal stack


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.76408648 0.85491233]
 [0.69198771 0.85163228]]
10
[4 6]
[3 7]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


##### Array Indexing and Slicing 

In [25]:
# array indexing
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

b = a[:2, 1:3]
print(b)

print(a[0, 1]) 

# changing the value of an element in b will change the value in a

b[0, 0] = 77
print(a[0, 1]) # prints 77 as the value is changed in b

# using boolean indexing
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)
print(bool_idx)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [45]:
# concatenating arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b), axis=0)) # concatenates along the first axis

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b.T), axis=1)) # concatenates along the second axis

[1 2 3 4 5 6]
[[1 2 5]
 [3 4 6]]


In [51]:
# mathematical functions
a = np.array([30, 45, 60, 90, 180])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

a = np.array([0, 0.5, 1])
print(np.arcsin(a))
print(np.arccos(a))
print(np.arctan(a))
print(np.degrees(a)) 

a = np.array([1, 2, 3])
print(np.exp(a))
print(np.log(a))
print(np.log10(a))

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.power(a, b))
print(np.mod(a, b))
print(np.floor_divide(a, b))


[-0.98803162  0.85090352 -0.30481062  0.89399666 -0.80115264]
[ 0.15425145  0.52532199 -0.95241298 -0.44807362 -0.59846007]
[-6.4053312   1.61977519  0.32004039 -1.99520041  1.33869021]
[0.         0.52359878 1.57079633]
[1.57079633 1.04719755 0.        ]
[0.         0.46364761 0.78539816]
[ 0.         28.64788976 57.29577951]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]
[0 0 0]


In [80]:
# linear algebra
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a)) # inverse of a
print(np.linalg.det(a)) # determinant of a
print(np.linalg.eig(a)) # eigenvalues and eigenvectors of a
print(np.linalg.svd(a)) # singular value decomposition of a
print(np.linalg.solve(a, np.array([5, 6]))) # solve the linear equation a*x = b

# matmul
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.matmul(a, b)) # matrix multiplication

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))
[-4.   4.5]
[[19 22]
 [43 50]]


In [53]:
# loading and saving data
a = np.array([[1, 2], [3, 4]])
np.save('my_array', a) # saves the array to my_array.npy
b = np.load('my_array.npy') # loads the array from my_array.npy
print(b)

[[1 2]
 [3 4]]


In [70]:
# Array statistics
a = np.array([1, 2, 2, 3, 4, 4])

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.argmin(a)) # index of the minimum element
print(np.argmax(a)) # index of the maximum element
print(np.percentile(a, 50)) # 50th percentile
print(np.any(a)) # True if any element is True
print(np.all(a)) # True if all elements are True
print(np.unique(a)) # unique elements in the array
print(np.bincount(a)) # number of occurrences of each value in the array


2.6666666666666665
2.5
1.1055415967851334
1.2222222222222223
1
4
0
4
2.5
True
True
[1 2 3 4]
[0 1 2 1 2]


In [81]:
# Random sampling
print(np.random.random(5)) # 5 random numbers between 0 and 1
print(np.random.randint(1, 10, 5)) # 5 random integers between 1 and 10
print(np.random.normal(0, 1, 5)) # 5 random numbers from a normal distribution with mean 0 and standard deviation 1
print(np.random.uniform(1, 2, 5)) # 5 random numbers between 1 and 2
print(np.random.permutation(5)) # random permutation of 0 to 4
print(np.random.choice(5, 5, replace=False)) # 5 random numbers from 0 to 4 without replacement
print(np.random.choice(5, 5, replace=True)) # 5 random numbers from 0 to 4 with replacement
print(np.random.choice(['a', 'b', 'c'], 5)) # 5 random elements from ['a', 'b', 'c']

[0.39697289 0.68089318 0.14881709 0.22210161 0.55645084]
[9 8 2 7 1]
[ 1.56622477 -0.26802519 -0.74362129 -0.13358027 -0.62167946]
[1.14328937 1.31192693 1.85829903 1.67905512 1.05490674]
[0 1 3 2 4]
[1 0 4 2 3]
[4 2 1 3 0]
['b' 'b' 'a' 'a' 'c']


In [87]:
# Array sorting
a = np.array([3, 1, 2, 4, 5])
print(np.sort(a)) # returns a new sorted array
print(a) # original array is unchanged

a.sort() # sorts the array in place
print(a)

a = np.array([[3, 1], [2, 4]])
print(np.sort(a, axis=0)) # sorts along the first axis
print(np.sort(a, axis=1)) # sorts along the second axis

[1 2 3 4 5]
[3 1 2 4 5]
[1 2 3 4 5]
[[2 1]
 [3 4]]
[[1 3]
 [2 4]]


In [91]:
# Array comparison
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

print(np.equal(a, b)) # elementwise comparison
print(np.not_equal(a, b)) # elementwise comparison
print(np.less(a, b)) # elementwise comparison
print(np.less_equal(a, b)) # elementwise comparison
print(np.greater(a, b)) # elementwise comparison
print(np.greater_equal(a, b)) # elementwise comparison
print(np.array_equal(a, b)) # True if arrays have the same shape and elements

[False False False False]
[ True  True  True  True]
[ True  True False False]
[ True  True False False]
[False False  True  True]
[False False  True  True]
False


In [110]:
# Array manipulation
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
print(np.reshape(a, (3, 2))) # reshapes the array to (3, 2)
print(np.ravel(a)) # flattens the array
print(np.transpose(a)) # transposes the array
print(np.split(a, 2)) # splits the array into 2 arrays
print(np.concatenate((a, b), axis=0)) # concatenates along the first axis
print(np.concatenate((a, b), axis=1)) # concatenates along the second axis
print(np.append(a, b)) # appends b to a
print(np.insert(a, 1, 5)) # inserts 5 at index 1
print(np.delete(a, 1)) # deletes element at index 1
print(np.flip(a)) # reverses the array
print(np.roll(a, 1)) # rolls the array by 1 element
print(np.repeat(a, 2)) # repeats each element twice

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 5 2 3 4 5 6]
[1 3 4 5 6]
[[6 5 4]
 [3 2 1]]
[[6 1 2]
 [3 4 5]]
[1 1 2 2 3 3 4 4 5 5 6 6]
[1 2 3 4 5 6]
